############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
weight = 2
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Blog"
url = "blog/"

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"

[[main]]
parent = "Pages"
name = "Authors"
url = "authors/"

[[main]]
parent = "Pages"
name = "Categories"
url = "categories/"

[[main]]
parent = "Pages"
name = "404 Page"
url = "404/"


# footer menu
# (none)
