### main config ###
baseURL = "/"                              # the base URL of site, prepended to all relative URLs
title = "opt-apps"                         # website title
theme = "hugoplate"                        # rheme name
timeZone = "America/New_York"              # default time zone for time stamps, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
paginate = 2                               # post pagination, see https://gohugo.io/extras/pagination/
summaryLength = 10                         # post excerpt length, see https://gohugo.io/content-management/excerpts/ 
googleAnalytics = "G-MEASUREMENT_ID"       # dee https://gohugo.io/templates/internal/#configure-google-analytics
disqusShortname = "themefisher-template"   # disqus can show comments in blog posts. To install, see https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
disableLanguages = []                      # for example, ["fr"] disables French. See https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false                     # if true, auto-detects Chinese/Japanese/Korean languages in content. See https://gohugo.io/getting-started/configuration/#hascjklanguage

### permalinks ###
[permalinks.page]
"pages" = "/:slugorfilename/"

### modules ###
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

### build ###
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

### outputs ###
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

### imaging ###
[imaging] # default JPEG & WebP quality setting. See https://github.com/disintegration/imaging
quality = 90
resampleFilter = "Lanczos"

### caches ###
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

### markup ###
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true

### media types ###
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

### output format ###
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

### plugins ###

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
lazy = true
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
lazy = true

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
lazy = false
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
lazy = false
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = true
[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true
[[params.plugins.js]]
link = "js/accordion.js"
lazy = true
[[params.plugins.js]]
link = "js/tab.js"
lazy = true
[[params.plugins.js]]
link = "js/modal.js"
lazy = true
[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = true
[[params.plugins.js]]
link = "plugins/youtube-lite.js"
lazy = true
